[tool.poetry]
name = "nudghub"
version = "0.1.0"
description = ""
authors = ["Gabriella Martin <gabriella.martin0101@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
